spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:prj301-assignment}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  servlet:
    context-path: /api/v1
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    image-size: 300
  error:
    include-message: always

jwt:
  expiration-time: ${JWT_EXPIRATION_TIME:604800000}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        type: trace
        orm:
          jdbc:
            bind: trace

aws:
  access_key_id: HLY6SEP9DZPC8TBA2E9N
  secret_access_key: ilfiBgerkFD06XU86Mct5YUQBscF15W3dMLTKffC
  region: hcm

s3:
  bucket: prj301
  endpoint: "https://hcm.ss.bfcplatform.vn"
  prefix: "https://prj301.hcm.ss.bfcplatform.vn/"
